Removed ESC from global shortcuts to locally handle it in dialog.
arduino/lab-micropython-editor pull request #168
Opened 2024-12-19 07:09 UTC by ubidefeo

I introduced a bug setting `ESC` as a global shortcut.
The `onKeyDown` event in the file-list would not be passed to the `<input>` field with the file/folder name to trigger a `.blur()` and cancel the creation of a file/folder

2024-12-19 09:55 UTC, sebromero requested changes
I don't think this can be handled easily from within ConnectionDialog. Either you make that a singleton instance or handle the key event from the outside (probably better)

2024-12-19 09:55 UTC, sebromero commented on ui/arduino/store.js
> +    // }
Please remove dead code

2024-12-19 09:57 UTC, sebromero commented
Plus I would use the key code to compare the pressed key 
```
const ESCAPE_KEY = 27
e.keyCode == ESCAPE_KEY
```

2024-12-21 23:49 UTC, ubidefeo commented
These changes are now part of a new branch

2024-12-21 23:49 UTC, closed without merging